build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:2.22.1
  amd64: ghcr.io/yeraze/meshmonitor:2.22.1
  armhf: ghcr.io/yeraze/meshmonitor:2.22.1
  armv7: ghcr.io/yeraze/meshmonitor:2.22.1
  i386: ghcr.io/yeraze/meshmonitor:2.22.1
