build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:3.4.6
  amd64: ghcr.io/yeraze/meshmonitor:3.4.6
  armhf: ghcr.io/yeraze/meshmonitor:3.4.6
  armv7: ghcr.io/yeraze/meshmonitor:3.4.6
  i386: ghcr.io/yeraze/meshmonitor:3.4.6
