build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:3.4.2
  amd64: ghcr.io/yeraze/meshmonitor:3.4.2
  armhf: ghcr.io/yeraze/meshmonitor:3.4.2
  armv7: ghcr.io/yeraze/meshmonitor:3.4.2
  i386: ghcr.io/yeraze/meshmonitor:3.4.2
