build_from:
  aarch64: ghcr.io/yeraze/meshmonitor:latest
  amd64: ghcr.io/yeraze/meshmonitor:latest
  armhf: ghcr.io/yeraze/meshmonitor:latest
  armv7: ghcr.io/yeraze/meshmonitor:latest
  i386: ghcr.io/yeraze/meshmonitor:latest
